version: '3.4'
services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - 50000:50000
      - 8080:8080
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins:
    name: jenkins
