version: '3.4'
services:
  jenkins:
    build: .
    container_name: jenkins
    ports:
      - 50000:50000
      - 8080:8080
    privileged: true
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run:/var/run:rw
      - /usr/bin/docker-compose:/usr/bin/docker-compose:rw
volumes:
  jenkins:
    name: jenkins
